export const Storage = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  GITHUB_STATE: "GITHUB_STATE",
  CODE: "CODE",
  INSTALLATION_ID: "INSTALLATION_ID",
  ACTIVE_CHANGES: "ACTIVE_CHANGES",
  PR_LINKS: "PR_LINKS",
  THREADS: "THREADS",
  FILE_REFS: "FILE_REFS",
} as const;
